framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async_redis:
                dsn: '%env(MESSENGER_TRANSPORT_DSN_REDIS)%'
            
            async_rabbit:
                dsn: '%env(MESSENGER_TRANSPORT_DSN_RABBIT)%'
                # options:
                #     exchange:
                #        name: high
                #     queues:
                #        messages_high: ~
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            # Route your messages to the transports
            'App\Message\SendEmailMessage': async_redis
            'App\Message\SmsNotification': async_rabbit
